<a href="https://colab.research.google.com/github/caroSF1/Extracci-n-de-datos/blob/main/Act1_2_Extracci%C3%B3n_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Carolina Solis Flores**
## **A01708072**

In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
files.upload()

In [38]:
df= pd.read_excel('Datos de FacturacioÃÅn.xlsx')

In [39]:
df.head()

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465.0,C,1.0,2019-09-03 08:58:42,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0
1,F29415,3926.0,C,1.0,2019-09-03 09:55:14,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
2,F29416,3926.0,C,1.0,2019-09-03 13:25:33,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
3,F29417,3926.0,C,1.0,2019-09-03 13:33:23,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0
4,F29418,6813.0,C,2.0,2019-09-03 14:23:45,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0

**1. CVE_CLPV(VALORES 1000:2000)**

In [40]:
fil1=df[(df["CVE_CLPV"] >= 1000) & (df["CVE_CLPV"] <= 2000)]
fil1

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
18,F29432,1965.0,C,2.0,2019-09-05 11:05:04.000,2019-09-05,2019-09-05 00:00:00,2019-09-20,2019-09-06,976.50,0.00,0
22,F29436,1965.0,C,2.0,2019-09-06 12:01:36.000,2019-09-06,2019-09-06 00:00:00,2019-09-21,2019-09-12,976.50,0.00,0
65,F29479,1240.0,E,2.0,2019-09-11 18:38:45.000,2019-09-11,2019-09-11 00:00:00,2019-09-11,NaT,4135.00,0.00,0
71,F29485,1965.0,C,2.0,2019-09-12 12:14:28.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,2019-09-12,976.50,146.48,0
72,F29486,1965.0,E,2.0,2019-09-12 12:25:52.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,NaT,976.50,146.48,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10821,F40237,1757.0,E,2.0,2023-02-24 15:18:17.570,2023-02-24,2023-02-13 00:00:00,2023-02-24,NaT,10088.40,0.00,0
10839,F40255,1583.0,E,2.0,2023-02-28 09:15:45.753,2023-02-28,2023-02-28 00:00:00,2023-03-30,NaT,3467.35,0.00,0
10845,F40261,1786.0,E,2.0,2023-02-28 11:15:32.527,2023-02-28,2023-03-03 00:00:00,2023-02-28,NaT,4663.80,0.00,0
10871,F40287,1453.0,E,1.0,2023-03-01 12:58:23.397,2023-03-01,2023-02-27 00:00:00,2023-03-31,NaT,9000.00,0.00,0
10876,F40292,1082.0,E,6.0,2023-03-02 11:00:54.770,2023-03-02,2023-03-01 00:00:00,2023-03-02,NaT,3262.00,0.00,0

**2.CVE_VEND(TODAS LAS CLAVES EXCEPTO "5" Y "4")**

In [41]:
fil2=df[~(df["CVE_VEND"] == "5") & ~(df["CVE_VEND"] == "4")]
fil2

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465.0,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0
1,F29415,3926.0,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
2,F29416,3926.0,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
3,F29417,3926.0,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0
4,F29418,6813.0,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10890,F40306,8842.0,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaT,3272.00,0.0,0
10891,F40307,6218.0,E,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,504.15,0.0,0
10892,F40308,5926.0,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,275.68,0.0,0
10893,F40309,361.0,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaT,129.30,0.0,0
10894,F40310,3011.0,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaT,517.20,0.0,0

**3. FECHA_ENT   (Fechas de ‚Äú28/02/2022‚Äù)**

In [42]:
fil3=df[df["FECHA_ENT"] == "28/02/2022  0:00:00"]
fil3

Empty DataFrame
Columns: [CVE_DOC, CVE_CLPV, STATUS, CVE_VEND, FECHAELAB, FECHA_DOC, FECHA_ENT, FECHA_VEN, FECHA_CANCELA, CAN_TOT, DES_TOT, DES_FIN]
Index: []

**4. CAN_TOT       (Cantidades menores a 5951.7)   o  STATUS (‚ÄúE‚Äù)**

In [43]:
fil4=df[(df["CAN_TOT"] < 5951.7) | (df["STATUS"] == "E")]
fil4

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465.0,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0
1,F29415,3926.0,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
2,F29416,3926.0,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
3,F29417,3926.0,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0
4,F29418,6813.0,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10890,F40306,8842.0,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaT,3272.00,0.0,0
10891,F40307,6218.0,E,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,504.15,0.0,0
10892,F40308,5926.0,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,275.68,0.0,0
10893,F40309,361.0,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaT,129.30,0.0,0
10894,F40310,3011.0,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaT,517.20,0.0,0

**5. Solo las columnas: CVE_DOC, FECHA_ENT, FECHA_VEN y CAN_TOT**

In [44]:
fil5=df.iloc[:,[0, 6, 7, 9]] 
fil5

      CVE_DOC            FECHA_ENT  FECHA_VEN  CAN_TOT
0      F29414  2019-09-03 00:00:00 2019-09-18  3980.00
1      F29415  2019-09-03 00:00:00 2019-10-03  1550.00
2      F29416  2019-09-03 00:00:00 2019-10-03  1550.00
3      F29417  2019-09-03 00:00:00 2019-10-03  1550.00
4      F29418  2019-09-03 00:00:00 2019-09-03  2435.44
...       ...                  ...        ...      ...
10890  F40306  2023-03-01 00:00:00 2023-03-06  3272.00
10891  F40307  2023-03-06 00:00:00 2023-03-06   504.15
10892  F40308  2023-03-06 00:00:00 2023-03-06   275.68
10893  F40309  2023-03-07 00:00:00 2023-03-07   129.30
10894  F40310  2023-03-01 00:00:00 2023-03-07   517.20

[10895 rows x 4 columns]

**6. Solo las filas de 7001-7099**

In [45]:
fil6 = df.iloc[ [7001, 7099] , : ]
fil6

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
7001,F36417,5271.0,E,3.0,2021-10-15 08:40:29.183,2021-10-15,2021-10-06 00:00:00,2021-11-14,NaT,8555.24,0.0,0
7099,F36515,5589.0,E,2.0,2021-10-27 14:04:26.797,2021-10-27,2021-10-26 00:00:00,2021-10-27,NaT,2106.00,0.0,0

**7. Index= CVE_VEND (valores: 1, 2)  (columna: FECHAELAB)**

In [46]:
df1= pd.read_excel('Datos de FacturacioÃÅn.xlsx', index_col=3)
df1

,CVE_DOC,CVE_CLPV,STATUS,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
CVE_VEND,,,,,,,,,,,
1.0,F29414,2465.0,C,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0
1.0,F29415,3926.0,C,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
1.0,F29416,3926.0,C,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
1.0,F29417,3926.0,C,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0
2.0,F29418,6813.0,C,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...
2.0,F40306,8842.0,E,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaT,3272.00,0.0,0
2.0,F40307,6218.0,E,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,504.15,0.0,0
2.0,F40308,5926.0,E,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,275.68,0.0,0
2.0,F40309,361.0,E,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaT,129.30,0.0,0
2.0,F40310,3011.0,E,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaT,517.20,0.0,0

In [47]:
fil7=df1.loc[[1.0,2.0], ["FECHAELAB"]]
fil7

                       FECHAELAB
CVE_VEND
1.0      2019-09-03 08:58:42.000
1.0      2019-09-03 09:55:14.000
1.0      2019-09-03 13:25:33.000
1.0      2019-09-03 13:33:23.000
1.0      2019-09-04 09:15:12.000
...                          ...
2.0      2023-03-06 16:09:39.013
2.0      2023-03-06 16:38:42.933
2.0      2023-03-06 17:02:33.390
2.0      2023-03-07 12:43:49.567
2.0      2023-03-07 12:45:58.407

[8665 rows x 1 columns]

**Convertirlo a CSV**

In [48]:
fil1.to_csv("Filtro1 CVE_CLPV.csv")
fil2.to_csv("Filtro2 CVE_VEND.csv")
fil3.to_csv("Filtro3 FECHA_ENT.csv")
fil4.to_csv("Filtro4 CAN_TOT.csv")
fil5.to_csv("Filtro5 Solo las columnas.csv")
fil6.to_csv("Filtro6 Solo las filas.csv")
fil7.to_csv("Filtro7 Index.csv")

In [49]:
#descardar archivo filtrado en csv
from google.colab import files 

files.download("Filtro1 CVE_CLPV.csv")
files.download("Filtro2 CVE_VEND.csv")
files.download("Filtro3 FECHA_ENT.csv")
files.download("Filtro4 CAN_TOT.csv")
files.download("Filtro5 Solo las columnas.csv")
files.download("Filtro6 Solo las filas.csv")
files.download("Filtro7 Index.csv")